{
	[9544776726] = { -- @AirBusFG15172 [Owner]
		["BANNABLE"] = true;
		["KICKABLE"] = true;
		["TIER"] = 10
	};
	[3434584503] = { -- @TseHongYeung0120 ( AirBusFG15172 ) [Owner]
		["BANNABLE"] = true;
		["KICKABLE"] = true;
		["TIER"] = 10
	};
	[2419843803] = { -- @Jonathanrfe23 (AirBusFG15712) [Owner]
		["BANNABLE"] = true;
		["KICKABLE"] = true;
		["TIER"] = 10
	};
	[3264020093] = { -- @Artem_123456red ( la_ttrn ) [Owner]
		["BANNABLE"] = true;
		["KICKABLE"] = true;
		["TIER"] = 10
	}
}
